# Generated by Django 3.1.1 on 2020-11-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi_UDE_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfigUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.FileField(upload_to='model_files/')),
                ('config', models.FileField(upload_to='config_files/')),
            ],
        ),
    ]
