# Generated by Django 3.1.1 on 2021-08-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi_UDE_v1', '0002_modelconfigupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udeupload',
            name='img',
            field=models.CharField(default='', max_length=256),
        ),
    ]
